name       : python-pyqt5-sip
version    : 12.11.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/P/PyQt5_sip/PyQt5_sip-12.11.0.tar.gz : b4710fd85b57edef716cc55fae45bfd5bfac6fc7ba91036f1dcc3f331ca0eb39
homepage   : https://pypi.org/project/PyQt5-sip/
license    : GPL-3.0-or-later
component  : programming.python
summary    : The sip module support for PyQt5
description: |
    The sip extension module provides support for the PyQt5 package.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
