name       : python-pyqt5-sip
version    : 12.10.1
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/P/PyQt5_sip/PyQt5_sip-12.10.1.tar.gz : 97e008795c453488f51a5c97dbff29cda7841afb1ca842c9e819d8e6cc0ae724
homepage   : https://pypi.org/project/PyQt5-sip/
license    : GPL-3.0-or-later
component  : programming.python
summary    : The sip module support for PyQt5
description: |
    The sip extension module provides support for the PyQt5 package.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
