name       : python-pyqt5-sip
version    : 12.9.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/P/PyQt5_sip/PyQt5_sip-12.9.0.tar.gz : d3e4489d7c2b0ece9d203ae66e573939f7f60d4d29e089c9f11daa17cfeaae32
homepage   : https://pypi.org/project/PyQt5-sip/
license    : GPL-3.0-or-later
component  : programming.python
summary    : The sip module support for PyQt5
description: |
    The sip extension module provides support for the PyQt5 package.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
